Adds PURL registration to H2 test.
sul-dlss/infrastructure-integration-test pull request #280
Opened 2021-07-06 21:47 UTC by justinlittman

closes #211

## Why was this change made?

## Was README.md updated if necessary?

## Are there any configuration changes for shared_configs?

2021-07-06 22:06 UTC, jcoyne requested changes

2021-07-06 22:06 UTC, jcoyne commented on spec/features/create_object_h2_spec.rb
> +    find_link("Choose Type and Edit #{item_title}").click
can you change this to `click_link`?

2021-09-08 00:31 UTC, ndushay approved these changes

2021-09-08 00:31 UTC, merged

2021-09-08 00:32 UTC, ndushay commented
@jcoyne merging this because JLitt took your suggestion and it's been hanging around since early July.