[WIP] new GIS integration test
sul-dlss/infrastructure-integration-test pull request #468
Opened 2022-07-29 19:32 UTC by peetucket

## Why was this change made? 🤔

Add a new integration test for accessioning GIS objects.  Fixes #16 

Still needs to be verified and tested in stage/qa.

2022-07-29 19:33 UTC, peetucket commented on spec/support/page_helpers.rb
>  end
allow us to use this method with a specific element on the page (useful for verifying specific workflow completion)

2022-07-29 23:16 UTC, peetucket commented on spec/features/create_gis_object_spec.rb
> +    test_data_destination_folder = File.join(Settings.gis.robots_content_root, bare_object_druid, 'temp')
note: this integration test data is currently just sitting on the server...another alternative is to place it in this codebase and then SCP up to the server each time it is run

2022-07-29 23:17 UTC, peetucket commented on spec/support/page_helpers.rb
>          else
this adds some extra functionality to this helper method to allow us to wait for text in a specific selector, useful for waiting for a specific workflow to complete

2022-08-02 16:45 UTC, ndushay reviewed
I'm about to put in a PR to rename the "create_xxx" spec files.   What do you think about calling the file `gis_accessioning_spec.rb` ?

2022-08-02 16:50 UTC, jcoyne commented
@ndushay I love the rename idea. If there are no other changes for this PR, you could merge this PR first and then do that rename in your PR.

2022-08-02 16:54 UTC, ndushay requested changes
Trying to run this on stage, there's an error in the normalize-data step.  See https://argo-stage.stanford.edu/view/druid:tj263wq9366

```
  1) Create and accession GIS object is expected not to have visible css ".alert-danger"
     Failure/Error: expect(page).not_to have_css('.alert-danger', wait: 0)
       expected not to find visible css ".alert-danger", found 1 match: "Error: normalize-data : 502 Bad Gateway"
     # ./spec/support/page_helpers.rb:34:in `block (2 levels) in reload_page_until_timeout!'
     # ./spec/support/page_helpers.rb:11:in `loop'
     # ./spec/support/page_helpers.rb:11:in `block in reload_page_until_timeout!'
     # ./spec/support/page_helpers.rb:10:in `reload_page_until_timeout!'
     # ./spec/features/create_gis_object_spec.rb:57:in `block (2 levels) in <top (required)>'
```

![image](https://user-images.githubusercontent.com/96775/182430156-5f989b25-dc41-498b-843a-93473961b1a4.png)

https://app.honeybadger.io/projects/52899/faults/87111228

Is this working in production?   Do we need https://spatialreference.org/ to allow connections from our gis-robots stage server?

2022-08-02 17:21 UTC, peetucket commented
1. I renamed the spec file.
2. I noticed the project tag was a bit different than other intergration test project tags, so I adjusted it slightly (not important for the test, but useful for finding the objects later)
3. The `https://spatialreference.org/` error is new as of this week and I don't think is under our control.  That appears to be an external domain/website that is actually down right now, which will block production accessioning of GIS objects too.

2022-08-04 16:11 UTC, ndushay approved these changes
Now that the external dependency is available, I got this to run.  Yay!

2022-08-04 16:11 UTC, merged